
package com.koreaaero.st;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ST00150_SO", targetNamespace = "http://koreaaero.com/ST")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ST00150SO {


    /**
     * 
     * @param mtST00150SEND
     * @return
     *     returns com.koreaaero.st.DTST00150SENDResponse
     */
    @WebMethod(operationName = "ST00150_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ST00150_SEND_response", targetNamespace = "http://koreaaero.com/ST", partName = "MT_ST00150_SEND_response")
    public DTST00150SENDResponse st00150SO(
        @WebParam(name = "MT_ST00150_SEND", targetNamespace = "http://koreaaero.com/ST", partName = "MT_ST00150_SEND")
        DTST00150SEND mtST00150SEND);

}
