-------------------------------------
-- 신규 버전 (2019.11.07)
-------------------------------------
SELECT	IC.OBJECT_ID			IC_SEND_OBJECT_ID
		, IC.FROMPARTY			IC_SEND_PARTY
		, IC.FROMSRVC			IC_SEND_COMPNM
		, IC.ACTIONNAME			IC_SEND_IFNM
		, IC.ACTIONNS			IC_SEND_IFNS
		, SENDCHAN.CHANNEL		IC_SEND_CHANNEL
		, SENDCHAN.ADAPTERTYPE	IC_SEND_ADAPTERTYPE
		, SENDCHAN.DIRECTION	IC_SEND_DIRECTION
		, SENDCHAN.MSGPROT		IC_SEND_MSGPROT
		, SENDCHAN.TRNSPROT		IC_SEND_TRNSPROT
		, ICTGT.OBJECT_ID		IC_RECV_OBJECT_ID
		, ICTGT.TOPARTY			IC_RECV_PARTY
		, ICTGT.TOSRVC			IC_RECV_COMPNM
		, ICTGT.ACTIONNAME		IC_RECV_IFNM
		, ICTGT.ACTIONNS		IC_RECV_IFNS
		, RECVCHAN.CHANNEL		IC_RECV_CHANNEL
		, RECVCHAN.ADAPTERTYPE	IC_RECV_ADAPTERTYPE
		, RECVCHAN.DIRECTION	IC_RECV_DIRECTION
		, RECVCHAN.MSGPROT		IC_RECV_MSGPROT
		, RECVCHAN.TRNSPROT		IC_RECV_TRNSPROT
FROM SAPSR3DB.XI_AF_CPA_BINDING IC
LEFT JOIN SAPSR3DB.XI_AF_CPA_CHANNEL SENDCHAN ON SENDCHAN.OBJECT_ID = IC.CHANNEL_ID
LEFT JOIN SAPSR3DB.XI_AF_CPA_BINDING ICTGT ON IC.OBJECT_ID = ICTGT.A1_OBJECT_ID AND IC.OBJECT_ID <> ICTGT.OBJECT_ID
LEFT JOIN SAPSR3DB.XI_AF_CPA_CHANNEL RECVCHAN ON RECVCHAN.OBJECT_ID = ICTGT.CHANNEL_ID
WHERE IC.DIRECTION = 'I'
--ORDER BY IC.FROMPARTY, IC.FROMSRVC, IC.ACTIONNAME, SENDCHAN.CHANNEL
;

-------------------------------------
-- 이전 버전 (2019.11.07)
-------------------------------------
SELECT	IC.OBJECT_ID
		--, IC.FROMPARTY
		--, IC.FROMSRVC
		--, IC.TOPARTY
		--, IC.TOSRVC
		--, IC.ACTIONNAME
		, IC.FROMPARTY || ' | ' || IC.FROMSRVC || ' | ' || IC.ACTIONNAME || ' | | ' AS IC_NM
		, '' AS IC_DESC
		, IC.FROMSRVC		IC_SEND_COMPNM
	--	, SENDCHAN.SERVICE	IC_SEND_SERVICE	
		, IC.ACTIONNAME		IC_SEND_IFNM
		, IC.ACTIONNS		IC_SEND_IFNS			
		--, IC.*
		, SENDCHAN.CHANNEL		IC_SEND_CHANNEL
		, SENDCHAN.ADAPTERTYPE	IC_SEND_ADAPTERTYPE
		, SENDCHAN.ADAPTERNS	IC_SEND_ADAPTERNS
		--, SENDCHAN.ADAPTERSWCV	IC_SEND_ADAPTERSWCV
		, SENDCHAN.DIRECTION	IC_SEND_DIRECTION
		, SENDCHAN.MSGPROT		IC_SEND_MSGPROT
		, SENDCHAN.MSGPROTVERS	IC_SEND_MSGPROTVERS
		, SENDCHAN.TRNSPROT		IC_SEND_TRNSPROT
		, SENDCHAN.TRNSPROTVERS	IC_SEND_TRNSPROTVERS
	--	, SENDCHAN.ATTRIBS		IC_SEND_ATTRIBS		
		--, SENDCHAN.*
		, ICTGT.TOSRVC			IC_RECV_COMPNM
	--	, RECVCHAN.SERVICE		IC_RECV_SERVICE	
		, ICTGT.ACTIONNAME		IC_RECV_IFNM
		, ICTGT.ACTIONNS		IC_RECV_IFNS	
	--, ICBINDTGT.ADAPTERTYPE	IC_RECV_ADAPTERTYPE
	--, ICBINDTGT.CHANNEL_ID	IC_RECV_CHANNEL_ID
		, RECVCHAN.CHANNEL		IC_RECV_CHANNEL
		, RECVCHAN.ADAPTERTYPE	IC_RECV_ADAPTERTYPE
		, RECVCHAN.ADAPTERNS	IC_RECV_ADAPTERNS
		--, RECVCHAN.ADAPTERSWCV	IC_RECV_ADAPTERSWCV
		, RECVCHAN.DIRECTION	IC_RECV_DIRECTION
		, RECVCHAN.MSGPROT		IC_RECV_MSGPROT
		, RECVCHAN.MSGPROTVERS	IC_RECV_MSGPROTVERS
		, RECVCHAN.TRNSPROT		IC_RECV_TRNSPROT
		, RECVCHAN.TRNSPROTVERS	IC_RECV_TRNSPROTVERS
	--	, RECVCHAN.ATTRIBS		IC_RECV_ATTRIBS			
FROM 	SAPSR3DB.XI_AF_CPA_BINDING IC
LEFT JOIN SAPSR3DB.XI_AF_CPA_CHANNEL SENDCHAN ON SENDCHAN.OBJECT_ID = IC.CHANNEL_ID
LEFT JOIN SAPSR3DB.XI_AF_CPA_BINDING ICTGT ON IC.OBJECT_ID = ICTGT.A1_OBJECT_ID AND IC.OBJECT_ID <> ICTGT.OBJECT_ID
LEFT JOIN SAPSR3DB.XI_AF_CPA_CHANNEL RECVCHAN ON RECVCHAN.OBJECT_ID = ICTGT.CHANNEL_ID
WHERE	IC.DIRECTION = 'I'
--AND		IC.FROMSRVC = 'KAD300' AND IC.ACTIONNAME = 'PP00180_SO' 
ORDER BY IC.FROMSRVC, IC.TOSRVC, IC.ACTIONNAME